### ISSUE TITLE
[RFC] Window$?

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#14]
This news is very encouraging: https://channel9.msdn.com/Events/Build/2016/C906

_I'm waiting for the next Windows 1y. :stuck_out_tongue:_

**Comment by ghost** [comment]
News: [PowerShell is open sourced and is available on Linux](https://azure.microsoft.com/en-us/blog/powershell-is-open-sourced-and-is-available-on-linux/)

Repo: https://github.com/PowerShell/PowerShell

**Comment by jakwings** [comment]
Perhaps...

Symlinks and CWD (current working directory) on Windows works differently from Unix. Bash/zsh has the $PWD trick, but still cannot fool `getcwd()`. Might be a problem. Another problem is special file names.

http://pubs.opengroup.org/onlinepubs/9699919799/functions/getcwd.html
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

**Comment by jakwings** [comment]
More notes:

* `C:file.txt\..` points to `C:` (Mind you, not `C:\`.), because `..` is resolved before symlinks.
* `C:\..` still points to `C:\`, just like the Unix way.
* [UNC] paths like `\\server\share\..` still points to the prefix `\\server\share`.
* `\\.\` is a special prefix for Win32 Device Namespaces.
* `\` for NT Namespaces.
* >  File I/O functions in the Windows API convert "/" to "\\" as part of converting the name to an NT-style name, except when using the "\\\\?\\" prefix as detailed in the following sections.


[UNC]: https://msdn.microsoft.com/en-us/library/gg465305.aspx
