### ISSUE TITLE
[RFC] Paths & Symbolic links

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#22]
What should we do if the GNU/BSD/… coreutils (ls, mv, cp, …) do not cope well with the shell when dealing with symlinks?
- Always resolve symlinks to absolute paths. (counter-intuition, does not solve the real problem)
- Rewrite the coreutils. (counter-tradition)

**Comment by jakwings** [comment]
Just hope it is unnecessary to deal with symlinks for the basic functionality. :-P

**Comment by jakwings** [comment]
Use absolute paths (without "." "..") for configuration files whenever possible.

**Comment by jakwings** [comment]
Quirks:

* `rm -R symlink/` will delete the linked directory instead of the symlink. `rm -R symlink` (without the slash) only delete the symlink.
* Some APIs treat a relative path `filename` different from `./filename`.

So, better append a slash `/` to a directory path, and prefix the relative path with `./` when suitable.

**Comment by jakwings** [comment]
Almost forgotten: HFS+ Unicode Normalization on MacOS.
